
* Summary
  I'm a cognitive and data scientist with more than 10 years of experience
  creating insights from large, complex datasets using computational tools, and
  communicating those insights to diverse stakeholders.  I have a passion for
  making computational tools broadly useful through open source software and
  straightforward and intuitive presentation of difficult computational ideas.

* Skills
  - Statistics (mixed-effects regression, nonparametric hypothesis testing)
  - Bayesian inference (MCMC, seqential MC, nonparametrics)
  - Data visualization
  - Machine learning
  - Git, Github, CI (Travis/Github actions)

* Programming languages
  - R (tidyverse, ggplot, lme4/brms, rstan)
  - Julia
  - stan (Bayesian modeling with HMC)
  - Javascript (node.js, JQuery/frontend)
  - Python
  - Matlab
  - Linux/bash/zsh

* Experience

** Assistant professor of Psychology

** Maintainer, JuliaStats
   Primary developer and maintainer of StatsModels.jl; contributor to
   Distributions.jl, GLM.jl, MixedModels.jl, etc.  Write code & documentation,
   provide support, manage testing, CI, and releases.
  
* Honors and Awards
  
* Education 
  PhD 
